NedTaxonomy =
  '*': 'Star'
  '**': 'Double Star'
  '*Ass': 'Stellar Association'
  '*Cl': 'Star Cluster'
  'AbLS': 'Absorption Line System'
  'Blue*': 'Blue Star'
  'C*': 'Carbon Star'
  'EmLS': 'Emission Line Source'
  'EmObj': 'Emission Object'
  'exG*': 'Isolated Star (Not A Member Of A Particular Galaxy)'
  'Flare*': 'Flare Star'
  'G': 'Galaxy'
  'GammaS': 'Gamma Ray Source'
  'GClstr': 'Cluster Of Galaxies'
  'GGroup': 'Group Of Galaxies'
  'GPair': 'Galaxy Pair'
  'GTrpl': 'Galaxy Triple'
  'G_Lens': 'Lensed Galaxy'
  'HII': 'Hii Region'
  'IrS': 'Infrared Source'
  'MCld': 'Molecular Cloud'
  'Neb': 'Nebula'
  'Nova': 'Nova'
  'Other': 'Other Classification (E.G. Comet; Plate Defect)'
  'PN': 'Planetary Nebula'
  'PofG': 'Part Of Galaxy'
  'Psr': 'Pulsar'
  'QGroup': 'Group Of Qsos'
  'QSO': 'Quasi-Stellar Object'
  'Q_Lens': 'Lensed Qso'
  'RadioS': 'Radio Source'
  'Red*': 'Red Star'
  'RfN': 'Reflection Nebula'
  'SN': 'Supernova'
  'SNR': 'Supernova Remnant'
  'UvES': 'Ultraviolet Excess Source'
  'V*': 'Variable Star'
  'VisS': 'Visual Source'
  'WD': 'White Dwarf'
  'WR': 'Wolf-Rayet Star'
  'XRayS': 'X-Ray Source'
  '!*': 'Galactic Star'
  '!**': 'Galactic Double Star'
  '!*Ass': 'Galactic Star Association'
  '!*Cl': 'Galactic Star Cluster'
  '!Blue*': 'Galactic Blue Star'
  '!C*': 'Galactic Carbon Star'
  '!EmObj': 'Galactic Emission Line Object'
  '!Flar*': 'Galactic Flare Star'
  '!HII': 'Galactic Hii Region'
  '!MCld': 'Galactic Molecular Cloud'
  '!Neb': 'Galactic Nebula'
  '!Nova': 'Galactic Nova'
  '!PN': 'Galactic Planetary Nebula'
  '!Psr': 'Galactic Pulsar'
  '!RfN': 'Galactic Reflection Nebula'
  '!Red*': 'Galactic Red Star'
  '!SN': 'Galactic Supernova'
  '!SNR': 'Galactic Supernova Remnant'
  '!V*': 'Galactic Variable Star'
  '!WD*': 'Galactic White Dwarf'
  '!WR*': 'Galactic Wolf-Rayet Star'

module.exports = NedTaxonomy  