SimbadTaxonomy =
  'Standard name': 'Extended Explanation'
  'Unknown': 'Object Of Unknown Nature'
  'Radio': 'Radio-Source'
  'Radio(m)': 'Metric Radio-Source'
  'Radio(cm)': 'Centimetric Radio-Source'
  'Radio(mm)': 'Millimetric Radio-Source'
  'Radio(sub-mm)': 'Sub-Millimetric Source'
  'HI': 'Hi (21Cm) Source'
  'radioBurst': 'Radio Burst'
  'Maser': 'Maser'
  'IR': 'Infra-Red Source'
  'IR>30um': 'Far-Ir Source (&lambda; >= 30 µM)'
  'IR<10um': 'Near-Ir Source (&lambda; < 10 µM)'
  'Red': 'Very Red Source'
  'RedExtreme': 'Extremely Red Object'
  'Blue': 'Blue Object'
  'UV': 'Uv-Emission Source'
  'X': 'X-Ray Source'
  'ULX?': 'Ultra-Luminous X-Ray Candidate'
  'ULX': 'Ultra-Luminous X-Ray Source'
  'gamma': 'Gamma-Ray Source'
  'gammaBurst': 'Gamma-Ray Burst'
  'Inexistent': '"Not An Object (Error, Artefact, ...) "'
  'Gravitation': 'Gravitational Source'
  'LensingEv': '(Micro)Lensing Event'
  'Candidate_LensSystem': 'Possible Gravitational Lens System'
  'Candidate_Lens': 'Possible Gravitational Lens'
  'Possible_lensImage': 'Possible Gravitationally Lensed Image'
  'GravLens': 'Gravitational Lens'
  'GravLensSystem': 'Gravitational Lens System (Lens+Images)'
  'Candidates': 'Candidate Objects'
  'Possible_SClG': 'Possible Supercluster Of Galaxies'
  'Possible_ClG': 'Possible Cluster Of Galaxies'
  'Possible_GrG': 'Possible Group Of Galaxies'
  'Candidate_**': 'Physical Binary Candidate'
  'Candidate_EB*': 'Eclipsing Binary Candidate'
  'Candidate_CV*': 'Cataclysmic Binary Candidate'
  'Candidate_XB*': 'X-Ray Binary Candidate'
  'Candidate_LMXB': 'Low-Mass X-Ray Binary Candidate'
  'Candidate_HMXB': 'High-Mass X-Ray Binary Candidate'
  'Candidate_Pec*': 'Possible Peculiar Star'
  'Candidate_YSO': 'Young Stellar Object Candidate'
  'Candidate_pMS*': 'Pre-Main Sequence Star Candidate'
  'Candidate_TTau*': 'T Tau Star Candidate'
  'Candidate_C*': 'Possible Carbon Star'
  'Candidate_S*': 'Possible S Star'
  'Candidate_OH': 'Possible Star With Envelope Of Oh/Ir Type'
  'Candidate_CH': 'Possible Star With Envelope Of Ch Type'
  'Candidate_WR*': 'Possible Wolf-Rayet Star'
  'Candidate_Be*': 'Possible Be Star'
  'Candidate_HB*': 'Possible Horizontal Branch Star'
  'Candidate_RRLyr': 'Possible Star Of Rr Lyr Type'
  'Candidate_Cepheid': 'Possible Cepheid'
  'Candidate_RGB*': 'Possible Red Giant Branch Star'
  'Candidate_SG*': 'Possible Supergiant Star'
  'Candidate_RSG*': 'Possible Red Supergiant Star'
  'Candidate_YSG*': 'Possible Yellow Supergiant Star'
  'Candidate_BSG*': 'Possible Blue Supergiant Star'
  'Candidate_AGB*': 'Possible Asymptotic Giant Branch Star'
  'Candidate_post-AGB*': 'Post-Agb Star Candidate'
  'Candidate_BSS': 'Candidate Blue Straggler Star'
  'Candidate_WD*': 'White Dwarf Candidate'
  'Candidate_NS': 'Neutron Star Candidate'
  'Candidate_BH': 'Black Hole Candidate'
  'Candidate_SN*': 'Supernova Candidate'
  'Candidate_low-mass*': 'Low-Mass Star Candidate'
  'Candidate_brownD*': 'Brown Dwarf Candidate'
  'multiple_object': 'Composite Object'
  'Region': 'Region Defined In The Sky'
  'Void': 'Underdense Region Of The Universe'
  'SuperClG': 'Supercluster Of Galaxies'
  'ClG': 'Cluster Of Galaxies'
  'GroupG': 'Group Of Galaxies'
  'Compact_Gr_G': 'Compact Group Of Galaxies'
  'PairG': 'Pair Of Galaxies'
  'IG': 'Interacting Galaxies'
  'GlCl?': 'Possible Globular Cluster'
  'Cl*': 'Cluster Of Stars'
  'GlCl': 'Globular Cluster'
  'OpCl': 'Open (Galactic) Cluster'
  'Assoc*': 'Association Of Stars'
  '**': 'Double Or Multiple Star'
  'EB*': 'Eclipsing Binary'
  'EB*Algol': 'Eclipsing Binary Of Algol Type'
  'EB*betLyr': 'Eclipsing Binary Of Beta Lyr Type'
  'EB*WUMa': 'Eclipsing Binary Of W Uma Type'
  'EB*Planet': 'Star Showing Eclipses By Its Planet'
  'SB*': 'Spectroscopic Binary'
  'CataclyV*': 'Cataclysmic Variable Star'
  'DQHer': 'Cataclysmic Var. Dq Her Type'
  'AMHer': 'Cataclysmic Var. Am Her Type'
  'Nova-like': 'Nova-Like Star'
  'Nova': 'Nova'
  'DwarfNova': 'Dwarf Nova'
  'XB': 'X-Ray Binary'
  'LMXB': 'Low Mass X-Ray Binary'
  'HMXB': 'High Mass X-Ray Binary'
  'ISM': 'Interstellar Matter'
  'PartofCloud': 'Part Of Cloud'
  'PN?': 'Possible Planetary Nebula'
  'ComGlob': 'Cometary Globule'
  'Bubble': 'Bubble'
  'EmObj': 'Emission Object'
  'Cloud': 'Cloud'
  'GalNeb': 'Galactic Nebula'
  'BrNeb': 'Bright Nebula'
  'DkNeb': 'Dark Cloud (Nebula)'
  'RfNeb': 'Reflection Nebula'
  'MolCld': 'Molecular Cloud'
  'Globule': 'Globule (Low-Mass Dark Cloud)'
  'denseCore': 'Dense Core Inside A Molecular Cloud'
  'HVCld': 'High-Velocity Cloud'
  'HII': 'Hii (Ionized) Region'
  'PN': 'Planetary Nebula'
  'HIshell': 'Hi Shell'
  'SNR?': 'Supernova Remnant Candidate'
  'SNR': 'Supernova Remnant'
  'Circumstellar': 'Circumstellar Matter'
  'outflow?': 'Outflow Candidate'
  'Outflow': 'Outflow'
  'HH': 'Herbig-Haro Object'
  'Star': 'Star'
  '*inCl': 'Star In Cluster'
  '*inNeb': 'Star In Nebula'
  '*inAssoc': 'Star In Association'
  '*in**': 'Star In Double System'
  'V*?': 'Star Suspected Of Variability'
  'Pec*': 'Peculiar Star'
  'HB*': 'Horizontal Branch Star'
  'YSO': 'Young Stellar Object'
  'Em*': 'Emission-Line Star'
  'Be*': 'Be Star'
  'BlueStraggler': 'Blue Straggler Star'
  'RGB*': 'Red Giant Branch Star'
  'AGB*': 'Asymptotic Giant Branch Star (He-Burning)'
  'C*': 'Carbon Star'
  'S*': 'S Star'
  'SG*': 'Evolved Supergiant Star'
  'RedSG*': 'Red Supergiant Star'
  'YellowSG*': 'Yellow Supergiant Star'
  'BlueSG**': 'Blue Supergiant Star'
  'post-AGB*': 'Post-Agb Star (Proto-Pn)'
  'WD*': 'White Dwarf'
  'pulsWD*': 'Pulsating White Dwarf'
  'low-mass*': 'Low-Mass Star (M<1Solmass)'
  'brownD*': 'Brown Dwarf (M<0.08Solmass)'
  'OH/IR': 'Star With Envelope Of Oh/Ir Type'
  'CH': 'Star With Envelope Of Ch Type'
  'pMS*': 'Pre-Main Sequence Star'
  'TTau*': 'T Tau-Type Star'
  'WR*': 'Wolf-Rayet Star'
  'PM*': 'High Proper-Motion Star'
  'HV*': 'High-Velocity Star'
  'V*': 'Variable Star'
  'Irregular_V*': 'Variable Star Of Irregular Type'
  'Orion_V*': 'Variable Star Of Orion Type'
  'Rapid_Irreg_V*': 'Variable Star With Rapid Variations'
  'Eruptive*': 'Eruptive Variable Star'
  'Flare*': 'Flare Star'
  'FUOr': 'Variable Star Of Fu Ori Type'
  'Erupt*RCrB': 'Variable Star Of R Crb Type'
  'RotV*': 'Rotationally Variable Star'
  'RotV*alf2CVn': 'Variable Star Of Alpha2 Cvn Type'
  'RotV*Ell': 'Ellipsoidal Variable Star'
  'Pulsar': 'Pulsar'
  'BYDra': 'Variable Of By Dra Type'
  'RSCVn': 'Variable Of Rs Cvn Type'
  'PulsV*': 'Pulsating Variable Star'
  'RRLyr': 'Variable Star Of Rr Lyr Type'
  'Cepheid': 'Cepheid Variable Star'
  'PulsV*delSct': 'Variable Star Of Delta Sct Type'
  'PulsV*RVTau': 'Variable Star Of Rv Tau Type'
  'PulsV*WVir': 'Variable Star Of W Vir Type'
  'PulsV*bCep': 'Variable Star Of Beta Cep Type'
  'deltaCep': 'Classical Cepheid (Delta Cep Type)'
  'gammaDor': 'Variable Star Of Gamma Dor Type'
  'pulsV*SX': 'Variable Star Of Sx Phe Type (Subdwarf)'
  'LPV*': 'Long-Period Variable Star'
  'Mira': 'Variable Star Of Mira Cet Type'
  'semi-regV*': 'Semi-Regular Pulsating Star'
  'SN': 'Supernova'
  'Symbiotic*': 'Symbiotic Star'
  'Sub-stellar': 'Sub-Stellar Object'
  'Planet?': 'Extra-Solar Planet Candidate'
  'Galaxy': 'Galaxy'
  'PartofG': 'Part Of A Galaxy'
  'GinCl': 'Galaxy In Cluster Of Galaxies'
  'BClG': 'Brightest Galaxy In A Cluster (Bcg)'
  'GinGroup': 'Galaxy In Group Of Galaxies'
  'GinPair': 'Galaxy In Pair Of Galaxies'
  'High_z_G': 'Galaxy With High Redshift'
  'AbsLineSystem': 'Absorption Line System'
  'Ly-alpha_ALS': 'Ly Alpha Absorption Line System'
  'DLy-alpha_ALS': 'Damped Ly-Alpha Absorption Line System'
  'metal_ALS': 'Metallic Absorption Line System'
  'Ly-limit_ALS': 'Lyman Limit System'
  'Broad_ALS': 'Broad Absorption Line System'
  'RadioG': 'Radio Galaxy'
  'HII_G': 'Hii Galaxy'
  'LSB_G': 'Low Surface Brightness Galaxy'
  'AGN_Candidate': 'Possible Active Galaxy Nucleus'
  'QSO_Candidate': 'Possible Quasar'
  'Blazar_Candidate': 'Possible Blazar'
  'BLLac_Candidate': 'Possible Bl Lac'
  'EmG': 'Emission-Line Galaxy'
  'StarburstG': 'Starburst Galaxy'
  'BlueCompG': 'Blue Compact Galaxy'
  'LensedImage': 'Gravitationally Lensed Image'
  'LensedG': 'Gravitationally Lensed Image Of A Galaxy'
  'LensedQ': 'Gravitationally Lensed Image Of A Quasar'
  'AGN': 'Active Galaxy Nucleus'
  'LINER': 'Liner-Type Active Galaxy Nucleus'
  'Seyfert': 'Seyfert Galaxy'
  'Seyfert_1': 'Seyfert 1 Galaxy'
  'Seyfert_2': 'Seyfert 2 Galaxy'
  'Blazar': 'Blazar'
  'BLLac': 'Bl Lac - Type Object'
  'OVV': 'Optically Violently Variable Object'
  'QSO': 'Quasar'

module.exports = SimbadTaxonomy